// <auto-generated />
namespace Wiki_Tunez.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class addingjunctiontable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addingjunctiontable));
        
        string IMigrationMetadata.Id
        {
            get { return "202107301405185_adding junction table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
